### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by bekircem** [ionutvmi/SublimeMybbTplEditor#10]
Hi.

I installed plugin. Templates work but when i edited CSS files dont work. How i fix that problem?

**Comment by ionutvmi** [comment]
Hi
Make sure you uploaded the  updatecss.php file to your server.
Then go to your settings file and make sure the http url is pointing to that update.css file

**Comment by bekircem** [comment]
Hi,

I am sure, updatecss.php is uploaded. Because template files is work for update, just css files not work.

**Comment by ionutvmi** [comment]
Well updatecss.php only updates the css files.
The template files are grabbed directly from the database so we don't need to refresh the cache for them.
Please check that the url is correct in your settings file. 
Another way you can check is by doing the css change the save and run the updatecss.php file from the browser.
Also make sure you clear your browser cache.

**Comment by ionutvmi** [comment]
Closing this issue since no feedback was provided.
