### ISSUE TITLE
Doesn't do anything after naming template folder - Potentially Windows 10

### ISSUE THREAD

**Issue by Igirisujin** [ionutvmi/SublimeMybbTplEditor#11]
I've installed the plugin and set up the settings to allow it to connect to the remote database. It seems to do so just fine as it correctly identifies the template sets when I run "Load Templates" within the plugin.

However, after selecting a template list and setting a folder name when prompted, the plugin simply doesn't do anything else. No folders are created in My Documents and no files are opened within sublime.

I've managed to isolate the issue to my windows 10 machine. The plugin works flawlessly on my windows 8.1 machine and I'll be using it on there in the mean time. However, it could potentially be other issues unrelated to the OS on my win 10 machine, though I can't seem to isolate any other cause. My guess is it's having issues creating the directory to download the files to but I'm unsure how to solve that personally.

**Comment by ionutvmi** [comment]
Interesting, I don't have a windows 10 machine to try that out.

Do you get any errors in the console ? (you can open that by pressing Ctrl + `)
Can you try running this command on your windows 10 machine ?
```
import os; os.path.expanduser("~\\My Documents\\")
```

**Comment by Igirisujin** [comment]
Traceback (most recent call last):
  File "mybb-tpl in C:\Users\Igiri\AppData\Roaming\Sublime Text 3\Installed Packages\Mybb Template Editor.sublime-package", line 64, in create_folder
  File "./os.py", line 269, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Igiri\\My Documents\\mybbTpl'

Looks like my hunch was right about it being unable to create the directory.

**Comment by ionutvmi** [comment]
Yes, I think they renamed that folder in windows 10.
As a temporary fix you can simply try to create a folder name `My Documents` inside your `C:\Users\Igiri\` folder and after that it should work as expected.

**Comment by Igirisujin** [comment]
Yeah I tried that, sorry should have said. Doesn't allow you to have a "My Documents" folder in the same folder as "Documents".

Seems to be a reserved folder name.
Perhaps add an option in the sublime-settings file to allow the user to define the directory the plugin saves to?

**Comment by ionutvmi** [comment]
I see, that explains why it fails to create the folder in the first place.

Yes I will add an option to allow users to set a custom path.

**Comment by Igirisujin** [comment]
Awesome, much appreciate. Thanks for the swift response on such an old project.

**Comment by ionutvmi** [comment]
In version 1.2.0 new option `default_path` was added where you can specify the default path for your directories.

You are also able to change that path when filling the folder name ![](http://puu.sh/kfVLn/e707ed6d58.png)

Please let me know if this fixes your issue.
It should get to you via package control in a few hours or you can install it manually now.

**Comment by Igirisujin** [comment]
Works flawlessly! Thank you so much for the swift update. This is an extremely useful plugin and it saves me a lot of time. Great work!
